language: python
python:
  - "3.6.2"
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install coveralls webtest
script:
  - python manage.py migrate
  - yes | python manage.py test
  - coverage run --source="." manage.py test
after_success: coveralls
