language: python
python:
  - "3.6.2"
install:
  - pip install -r requirements.txt
  - pip install coveralls webtest
script:
  - python manage.py migrate
  - python manage.py test
  - coverage run --source="." manage.py test
after_success: coveralls
