dist: bionic
language: python
python:
  - "3.7.3"
services:
  - redis-server
install:
  - pip install -r dev_requirements.txt
  - pip install coveralls
script:
  - python manage.py migrate
  - yes | python manage.py test
  - coverage run --source="." manage.py test
after_success: coveralls
