# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('a2code', models.CharField(max_length=2)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Continent')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='JobsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs Data',
            },
        ),
        migrations.CreateModel(
            name='SourceLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Country')),
            ],
            options={
                'verbose_name_plural': 'Source Links',
            },
        ),
        migrations.AddField(
            model_name='jobsdata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.SourceLinks'),
        ),
    ]
