# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20151203_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdata',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='search.SourceLinks', to_field='url'),
        ),
        migrations.AlterField(
            model_name='sourcelinks',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
