# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160222_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdata',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='sourcelinks',
            name='url',
            field=models.URLField(),
        ),
    ]
